Repository torchbox/rca-wagtail-2019, pull requests merged in 2020-05, with the labels that each got.

#387 refactor alumni stories and news/events to use a management command t…
  rca/api_content/content.py
  rca/api_content/management/__init__.py
  rca/api_content/management/commands/__init__.py
  rca/api_content/management/commands/fetch_api_content.py
  rca/home/models.py
  rca/programmes/models.py
Labels: to-deploy

#389 Provide a template filter for checking internal or external links
  rca/project_styleguide/templates/patterns/atoms/link-tertiary/link-tertiary--external.html
  rca/project_styleguide/templates/patterns/atoms/link-tertiary/link-tertiary--link.html
  rca/project_styleguide/templates/patterns/atoms/sprites/sprites.html
  rca/project_styleguide/templates/patterns/molecules/profile-detail/profile-detail.html
  rca/project_styleguide/templates/patterns/pages/staff/staff_detail.yaml
  rca/static_src/sass/components/_link.scss
  rca/utils/templatetags/util_tags.py
  rca/utils/tests/__init__.py
  rca/utils/tests/test_template_tags.py
Labels: on-dev

#370 403 Implements fields for guide page
  rca/guides/migrations/0002_guide_base_fields.py
  rca/guides/migrations/0003_add_related_pages_title.py
  rca/guides/migrations/0004_field_alterations.py
  rca/guides/migrations/0005_specifc_streamfield_for_guides.py
  rca/guides/migrations/0006_extra_title_field.py
  rca/guides/models.py
  rca/project_styleguide/templates/patterns/molecules/card/card.html
  rca/project_styleguide/templates/patterns/molecules/profile-detail/profile-detail.html
  rca/project_styleguide/templates/patterns/molecules/streamfield/blocks/anchor_heading_block.html
  rca/project_styleguide/templates/patterns/molecules/streamfield/blocks/anchor_heading_block.yaml
  rca/project_styleguide/templates/patterns/molecules/streamfield/blocks/image_block.html
  rca/project_styleguide/templates/patterns/organisms/index-module/index-module.html
  rca/project_styleguide/templates/patterns/organisms/index-module/index-module.yaml
  rca/project_styleguide/templates/patterns/pages/guide/guide.html
  rca/project_styleguide/templates/patterns/pages/guide/guide.yaml
  rca/utils/blocks.py
  rca/utils/models.py
Labels: on staging

#391 Feature/396 application form link
  rca/project_styleguide/templates/patterns/molecules/upcoming-dates/upcoming-dates.html
  rca/shortcourses/migrations/0013_add_application_link.py
  rca/shortcourses/models.py
Labels: on-dev

#398 Feature/376 research highlights
  rca/project_styleguide/templates/patterns/pages/researchcentre/research_centre.html
  rca/research/migrations/0006_add_configurable_title_field.py
  rca/research/migrations/0007_add_curatable_project_relationship.py
  rca/research/models.py
Labels: on-dev

#388 If a title value isn't added, we should get the title from the page v…
  rca/navigation/models.py
Labels: on staging

#405 Feature/433 type output
  rca/research/models.py
Labels: on staging
