Repository torchbox/rca-wagtail-2019, pull requests merged in 2020-06, with the labels that each got.

#426 Feature/p2 450 staff detail
  rca/people/migrations/0002_add_base_fields_for_staff_profile.py
  rca/people/migrations/0003_improve_relationships_between_models.py
  rca/people/models.py
  rca/project_styleguide/templates/patterns/molecules/key-details/key-details--staff.html
  rca/project_styleguide/templates/patterns/molecules/key-details/key-details--staff.yaml
  rca/project_styleguide/templates/patterns/pages/staff/staff_detail.html
  rca/project_styleguide/templates/patterns/pages/staff/staff_detail.yaml
  rca/projects/migrations/0010_improve_relationships_between_models.py
  rca/projects/migrations/0011_fix_page_fk.py
  rca/projects/models.py
  rca/research/migrations/0008_improve_relationships_between_models.py
  rca/research/models.py
  rca/schools/migrations/0003_improve_relationships_between_models.py
  rca/schools/models.py
  rca/settings/base.py
  rca/utils/wagtail_hooks.py
Labels: on-dev

#431 Stop populating a full non-https link
  rca/projects/models.py
Labels: on-dev

#437 Feature/p2 455 staff student relationship
  rca/api_content/content.py
  rca/api_content/management/commands/fetch_api_content.py
  rca/people/migrations/0005_staffpagemanualrelatedstudents.py
  rca/people/migrations/0006_remove_staffpage_job_title.py
  rca/people/models.py
  rca/project_styleguide/templates/patterns/pages/staff/staff_detail.html
  rca/project_styleguide/templates/patterns/pages/staff/staff_detail.yaml
Labels: on-dev

#428 Feature/p2 478 staff roles
  rca/people/migrations/0007_staffrole.py
  rca/people/models.py
  rca/programmes/models.py
  rca/project_styleguide/templates/patterns/molecules/job-titles/job-titles.html
  rca/project_styleguide/templates/patterns/molecules/job-titles/job-titles.yaml
  rca/project_styleguide/templates/patterns/pages/staff/staff_detail.html
Labels: on-dev

#438 [454] Staff data migration (CSV import)
  rca/api_content/content.py
  rca/people/admin/__init__.py
  rca/people/admin/page_import.py
  rca/people/admin/page_import_forms.py
  rca/people/models.py
  rca/people/templates/admin/import_export/page_import.html
  rca/settings/base.py
  requirements.txt
Labels: on-dev

#446 Adds external links to the project page
  .isort.cfg
  rca/project_styleguide/templates/patterns/pages/project/project_detail.html
  rca/projects/migrations/0012_projectpage_external_links.py
  rca/projects/models.py
Labels: on-dev

#409 286 Add short courses to the programmes listing API and results views
  rca/programmes/models.py
  rca/shortcourses/models.py
  rca/static_src/javascript/programmes/components/ProgrammesCategories/CategoriesPanels.js
  rca/static_src/javascript/programmes/components/ProgrammesExplorer.js
  rca/static_src/javascript/programmes/components/ProgrammesResults/ProgrammeTeaser.js
  rca/static_src/javascript/programmes/components/ProgrammesResults/ProgrammeTeaser.test.js
  rca/static_src/javascript/programmes/components/ProgrammesResults/ProgrammesResults.js
  rca/static_src/javascript/programmes/programmes.api.js
  rca/static_src/javascript/programmes/programmes.slice.js
  rca/static_src/javascript/programmes/programmes.types.js
Labels: enhancement

#441 [445] Overlay link behaviour
  rca/static_src/javascript/components/modal.js
Labels: on-dev

#447 [460] Active anchor nav
  rca/project_styleguide/templates/patterns/molecules/anchor-nav/anchor-nav.html
  rca/project_styleguide/templates/patterns/organisms/accordion-block/accordion-block.html
  rca/project_styleguide/templates/patterns/organisms/contact/contact.html
  rca/project_styleguide/templates/patterns/organisms/index-module/index-module.html
  rca/project_styleguide/templates/patterns/organisms/people-module/people-module.html
  rca/project_styleguide/templates/patterns/pages/guide/guide.html
  rca/static_src/javascript/components/anchor-nav.js
  rca/static_src/javascript/main.entry.js
  rca/static_src/sass/components/_anchor-nav-item.scss
Labels: on-dev

#456 Feature/286 search
  rca/shortcourses/models.py
Labels: on-dev

#460 Expose highlight page link for default landing page type
  rca/landingpages/migrations/0017_landingpage_highlights_page_link_title.py
  rca/landingpages/models.py
  rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--enterprise.html
  rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--generic.html
  rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--innovation.html
  rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--research.html
Labels: on staging

#459 471 Project picker page fixes
  rca/people/migrations/0009_areaofexpertise_slug.py
  rca/people/models.py
  rca/projects/migrations/0015_init_taxonomy_slugs.py
  rca/projects/models.py
  rca/utils/migrations/0014_add_research_type_slug.py
  rca/utils/models.py
Labels: on staging
